# Generated by Django 2.1.3 on 2018-12-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('addr', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('imgSrc', models.URLField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hol', models.BooleanField()),
                ('day', models.CharField(max_length=10)),
                ('open', models.TimeField(blank=True, null=True)),
                ('close', models.TimeField(blank=True, null=True)),
                ('last', models.TimeField(blank=True, null=True)),
                ('day_note', models.CharField(max_length=50)),
                ('etc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='eat',
            name='time',
            field=models.ManyToManyField(blank=True, related_name='time', to='eats.Hour'),
        ),
    ]
